openapi: 3.0.3
info:
  title: MEDICAL
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:5733'
paths:
  /api/v1/user:
    get:
      summary: ''
      operationId: getApiV1User
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
